### ISSUE TITLE
lambda functions in circuits DSL are binary functions

### ISSUE THREAD

**Issue by kataph** [nathanael-fijalkow/DeepSynth#5]
A very minor issue, but it caused me some time to realize. 

In the circuit DSL the boolean binary functions are defined this way:
```
semantics = {
	'and' : lambda bool1, bool2: bool1 and bool2,
	'or'  : lambda bool1, bool2: bool1 or bool2,
	'xor' : lambda bool1, bool2: bool1^bool2,
	'not' : lambda bool: not bool
}
```
instead of in this way:
```
semantics = {
	'and' : lambda bool1: lambda bool2: bool1 and bool2,
	'or'  : lambda bool1: lambda bool2: bool1 or bool2,
	'xor' : lambda bool1: lambda bool2: bool1^bool2,
	'not' : lambda bool: not bool
}
```
This is actually also mentioned in the readme ("One important point: when defining the semantics of functions, Python must be able to evaluate them one argument at a time"). Being evaluated two arguments at a time causes a 'silenced' error during program evaluation (the program is quietly evaluated to `None`).

**Comment by nathanael-fijalkow** [comment]
Thanks, approved!
